"""ResolutionReport → 파일/PR 본문 마크다운 변환."""
from common.models import ResolutionReport


def incident_markdown(report: ResolutionReport) -> str:
    """`incidents/<id>.md` 에 기록될 본문."""
    return (
        f"# Incident {report.incident_id}\n\n"
        f"- **Severity**: {report.severity.value.upper()}\n"
        f"- **Created**: {report.created_at.isoformat()}\n\n"
        f"## Triage Summary\n\n{report.triage_summary}\n\n"
        f"## Root Cause\n\n{report.root_cause}\n\n"
        f"## Patch Suggestion\n\n```\n{report.patch_suggestion}\n```\n\n"
        f"## Post-Mortem Draft\n\n{report.post_mortem_draft}\n"
    )


def pr_body(report: ResolutionReport) -> str:
    """PR description."""
    return (
        f"AI Agent 분석 결과로 생성된 인시던트 리포트입니다.\n\n"
        f"- **Incident ID**: `{report.incident_id}`\n"
        f"- **Severity**: `{report.severity.value.upper()}`\n\n"
        f"## Triage\n{report.triage_summary}\n\n"
        f"## Root Cause\n{report.root_cause}\n\n"
        f"## Patch Suggestion\n```\n{report.patch_suggestion}\n```\n\n"
        f"---\n"
        f"_Generated by warroom AI Agent. Please review before merging._\n"
    )


def pr_title(report: ResolutionReport) -> str:
    return f"[warroom] {report.severity.value.upper()} 인시던트 분석: {report.incident_id}"


def branch_name(report: ResolutionReport) -> str:
    ts = report.created_at.strftime("%Y%m%d-%H%M%S")
    return f"warroom/incident-{report.incident_id}-{ts}"
