"""ResolutionReport → 파일/PR 본문 마크다운 변환.

patch_suggestion 은 orchestrator 에서 raw 로 저장돼 있다 (diff 구조 보존을
위해 redact 미적용 — secrets.md § 3 참조). 여기 렌더링 단계에서 redact
적용해 incidents/<id>.md 와 PR body 모두 안전.
"""

from common.models import ResolutionReport
from common.redact import redact_secrets


def incident_markdown(report: ResolutionReport) -> str:
    """`incidents/<id>.md` 에 기록될 본문.

    patch_suggestion 은 Fixer 가 직접 ` ```diff ... ``` ` 으로 감싸 출력하므로
    여기서 다시 fencing 하지 않는다 (중첩 시 마크다운 렌더 깨짐).
    """
    patch_safe = redact_secrets(report.patch_suggestion)
    return (
        f"# Incident {report.incident_id}\n\n"
        f"- **Severity**: {report.severity.value.upper()}\n"
        f"- **Created**: {report.created_at.isoformat()}\n\n"
        f"## Triage Summary\n\n{report.triage_summary}\n\n"
        f"## Root Cause\n\n{report.root_cause}\n\n"
        f"## Patch Suggestion\n\n{patch_safe}\n\n"
        f"## Post-Mortem Draft\n\n{report.post_mortem_draft}\n"
    )


def pr_body(report: ResolutionReport) -> str:
    """PR description."""
    patch_safe = redact_secrets(report.patch_suggestion)
    return (
        f"AI Agent 분석 결과로 생성된 인시던트 리포트입니다.\n\n"
        f"- **Incident ID**: `{report.incident_id}`\n"
        f"- **Severity**: `{report.severity.value.upper()}`\n\n"
        f"## Triage\n{report.triage_summary}\n\n"
        f"## Root Cause\n{report.root_cause}\n\n"
        f"## Patch Suggestion\n{patch_safe}\n\n"
        f"---\n"
        f"_Generated by warroom AI Agent. Please review before merging._\n"
    )


def pr_title(report: ResolutionReport) -> str:
    return f"[warroom] {report.severity.value.upper()} 인시던트 분석: {report.incident_id}"


def branch_name(report: ResolutionReport) -> str:
    ts = report.created_at.strftime("%Y%m%d-%H%M%S")
    return f"warroom/incident-{report.incident_id}-{ts}"
